language: erlang
branches:
  only:
    - master
notifications:
  email: arcusfelis@gmail.com
  irc: 
env:
  - R16B
  - R15B03
  - R15B02
  - R15B01
  - R15B
  - R14B04
  - R14B03
  - R14B02
  - R14B01
  - R14A
  - R13B04

